# docker-compose.yml
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: quizard-app:latest
    ports:
      - "5000:5000"
    env_file:
      - .env  # Use environment variables defined in the .env file
    volumes:
      - ./src:/src  # Mount the backend directory to the app directory in the container
    command: python -m src.rest.flask_app
    depends_on:
      - rabbitmq
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: quizard-app:latest
    depends_on:
      - web
      - redis
      - rabbitmq
    command: celery -A src.celery.celery_worker worker -l info
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "8080:15672"  # Management interface (only for dev)
      - "5672:5672"   # RabbitMQ server
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"