# config/run_config.yaml
# deprecated - used for local testing without building the docker image
text_input: "bullet_point_summary/DOE_GER.txt"    # path from within the input folder e.g. text_summary/...
run_name: "run33a-backend_cleanup.csv"
model_name: "gpt-3.5-turbo"              # TODO: Test gpt-3.5-turbo-0125 vs. gpt-3.5-turbo-instruct
lang: "de"
mode: "practice"



# 07.02.2024 Model overview:
# gpt-3.5-turbo-instruct:       context:    4K;   input: $0.0015 / 1K tokens;   output: $0.0020 / 1K tokens
# gpt-3.5-turbo-0125:           context:   16K;   input: $0.0005 / 1K tokens;   output: $0.0015 / 1K tokens
# gpt-4-0125-preview	        context:  128K;   input: $0.0005 / 1K tokens;   output: $0.0015 / 1K tokens
# gpt-4-0125-vision-preview	    context:  128K;   input: $0.0005 / 1K tokens;   output: $0.0015 / 1K tokens (additional overhead for vision)
# gpt-4 	                    context:   16K;   input: $0.0300 / 1K tokens;   output: $0.0600 / 1K tokens
# gpt-4-32k         	        context:   32K;   input: $0.0600 / 1K tokens;   output: $0.1200 / 1K tokens